server:
  port: 9090
  servlet:
    context-path: /admin
spring:
  application:
    name: admin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.3.20:3306/admin #172.17.0.3
    username: root
    password: root
  data:
    jpa:
      repositories:
        enabled: true 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect #org.hibernate.dialect.MySQLInnoDBDialect
        format_sql: true
        enable_lazy_load_no_trans: true
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8083/auth/realms/baeldung
#          jwk-set-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/certs
